### ISSUE TITLE
squarring algorithm

### ISSUE THREAD

**Issue by remtav** [eurostat/EuroGeoStat#10]
Hi! 
Are you still maintaining the squarring algorithm mentionned [here](https://gis.stackexchange.com/questions/25263/is-there-any-open-source-building-squaring-tool/318756#318756?newreg=61c024d7701e4bdbadcfd242265c07a4)?
I found it in a [an old commit](https://sourceforge.net/p/opencarto/code/1201/tree/trunk/server/src/main/java/org/opencarto/algo/Squarring.java) and would like to run so experiments with it. Thanks!

**Comment by jgaffuri** [comment]
Hi! Yes, it is still maintained, even if I have not used it for 2 years. The test still pass ! Let me know if you see any problem.
I have updated the links there https://gis.stackexchange.com/a/25268/162
